feat!: Update to Uno5
nventive/Reactive.Annex pull request #66
Opened 2023-12-21 16:07 UTC by juliecantin

GitHub Issue: #

## Proposed Changes

 - [ ] Bug fix
 - [x] Feature
 - [ ] Code style update (formatting)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build or CI related changes
 - [ ] Documentation content changes
 - [ ] Other, please describe:

## What is the current behavior?
Reactive.Annex targets Uno 4 and .net 6

## What is the new behavior?
Reactive.Annex targets Uno 5 and .net 7

## Impact on version

- [x] **Major** (Public API was modified.)
  - Public constructs (class, struct, delegate, enum, etc.) were removed or renamed.
  - Public members were removed or renamed.
  - Public method signatures were changed or renamed.
- [ ] **Minor** (Public API was extended.)
  - Public constructs, members, or overloads were added.
- [ ] **Patch** (Public API was unchanged.)
  - A bug in behavior was fixed.
  - Documentation was changed.
- [ ] **None** (The library is unchanged.)
  - Only code under the `build` folder was changed.
  - Only code under the `.github` folder was changed.

## Checklist

Please check that your PR fulfills the following requirements:

- [x] Documentation has been added/updated.
  - README.md was reviewed.
  - [BREAKING_CHANGES.md](../BREAKING_CHANGES.md) was updated (if you introduced a breaking change).
- [ ] Automated Unit / Integration tests for the changes have been added/updated.
- [x] Your conventional commits are aligned with the **Impact on version** section.

Apps which use this new version of Reactive.Annex will need to [update to Uno 5](https://platform.uno/docs/articles/migrating-to-uno-5.html).

## Other information

2023-12-21 17:56 UTC, jeanplevesque approved these changes

2023-12-21 18:25 UTC, jeanplevesque requested changes

2023-12-21 18:25 UTC, jeanplevesque commented on src/Reactive.Annex.Uno.WinUI/Reactive.Annex.Uno.WinUI.csproj
> -  <PropertyGroup Condition="'$(TargetFramework)'=='netstandard2.0'">
Keep WASM.

2023-12-23 19:30 UTC, jeanplevesque approved these changes

2024-01-02 14:05 UTC, carlh98 approved these changes

2024-01-02 14:05 UTC, merged